common scripts: add xip related tests in regression
Signed-off-by: vivi.li <vivi.li@analog.com>

diff --git a/common/kernel_test b/common/kernel_test
--- a/common/kernel_test
+++ b/common/kernel_test
@@ -105,9 +105,9 @@ BUILD_POLICY=1
 
 n=100
 
-AUTO_TESTCASE=( [0]="ethernet" [1]="bfindma" [2]="sd" [3]="usb_storage" [4]="audio" [5]="qt" [6]="lmbench" [7]="nbench" [8]="dhrystone" [9]="whetstone" [10]="edn" [11]="dmacopy" [12]="earlyprintk" [13]="l1_module" [14]="l1_app" [15]="erestart" [16]="pthread" [17]="traps" [18]="module" [19]="boot_addr" [20]="strace" [21]="ramfs" [22]="stress" [23]="kgdb" [24]="sdiommc" [25]="null_point" [26]="watchdog" [27]="malloc_perf" [28]="fixed_code" [29]="l2_app" [30]="l2_module" [31]="sqlite" [32]="g729" [33]="mem_fragment" [34]="bfincrc" [35]="ethernet_in_buffer" [36]="reserve_mem" [37]="mmap" [38]="gptimer" [39]="nfs" [40]="smbfs" [41]="shared_flat"  [42]="string" [43]="usb_camera" [44]="audio_adau1761" [45]="pound" [46]="dll" [47]="linphone_adau1761" [48]="linkport" [49]="bluetooth" [50]="pnormtd" [51]="jffs2" [52]="jffs2_fs" [53]="camera" [$((n+1))]="serial" [$((n+2))]="ltp" [$((n+3))]="ethernet_usb" [$((n+4))]="timer" [$((n+5))]="usbdev" [$((n+6))]="snormtd" [$((n+7))]="usbhost" [$((n+8))]="usbotg"  [$((n+9))]="serial_uart" [$((n+10))]="snormtd_ext" )
+AUTO_TESTCASE=( [0]="ethernet" [1]="bfindma" [2]="sd" [3]="usb_storage" [4]="audio" [5]="qt" [6]="lmbench" [7]="nbench" [8]="dhrystone" [9]="whetstone" [10]="edn" [11]="dmacopy" [12]="earlyprintk" [13]="l1_module" [14]="l1_app" [15]="erestart" [16]="pthread" [17]="traps" [18]="module" [19]="boot_addr" [20]="strace" [21]="ramfs" [22]="stress" [23]="kgdb" [24]="sdiommc" [25]="null_point" [26]="watchdog" [27]="malloc_perf" [28]="fixed_code" [29]="l2_app" [30]="l2_module" [31]="sqlite" [32]="g729" [33]="mem_fragment" [34]="bfincrc" [35]="ethernet_in_buffer" [36]="reserve_mem" [37]="mmap" [38]="gptimer" [39]="nfs" [40]="smbfs" [41]="shared_flat"  [42]="string" [43]="usb_camera" [44]="audio_adau1761" [45]="pound" [46]="dll" [47]="linphone_adau1761" [48]="linkport" [49]="bluetooth" [50]="pnormtd" [51]="jffs2" [52]="jffs2_fs" [53]="camera" [$((n+1))]="serial" [$((n+2))]="ltp" [$((n+3))]="ethernet_usb" [$((n+4))]="timer" [$((n+5))]="usbdev" [$((n+6))]="snormtd" [$((n+7))]="usbhost" [$((n+8))]="usbotg"  [$((n+9))]="serial_uart" [$((n+10))]="snormtd_ext" [$((n+11))]="xip" )
 
-AUTO_RUN_STATUS=( [0]="1" [1]="0" [2]="0" [3]="0" [4]="0" [5]="0" [6]="1" [7]="1" [8]="1" [9]="1" [10]="1" [11]="0" [12]="0"  [13]="1" [14]="1" [15]="1" [16]="1" [17]="1" [18]="1" [19]="1" [20]="1" [21]="1" [22]="1" [23]="1" [24]="0" [25]="1" [26]="1" [27]="1" [28]="1" [29]="0" [30]="0" [31]="1" [32]="1" [33]="1" [34]="0" [35]="1" [36]="1" [37]="1" [38]="0" [39]="1" [40]="1" [41]="1" [42]="1" [43]="0" [44]="0" [45]="0" [46]="1" [47]="0" [48]="0" [49]="0" [50]="0" [51]="0" [52]="0" [53]="0" [$((n+1))]="1" [$((n+2))]="1" [$((n+3))]="0" [$((n+4))]="0" [$((n+5))]="0" [$((n+6))]="0" [$((n+7))]="0" [$((n+8))]="0" [$((n+9))]="0" [$((n+10))]="0" )
+AUTO_RUN_STATUS=( [0]="1" [1]="0" [2]="0" [3]="0" [4]="0" [5]="0" [6]="1" [7]="1" [8]="1" [9]="1" [10]="1" [11]="0" [12]="0"  [13]="1" [14]="1" [15]="1" [16]="1" [17]="1" [18]="1" [19]="1" [20]="1" [21]="1" [22]="1" [23]="1" [24]="0" [25]="1" [26]="1" [27]="1" [28]="1" [29]="0" [30]="0" [31]="1" [32]="1" [33]="1" [34]="0" [35]="1" [36]="1" [37]="1" [38]="0" [39]="1" [40]="1" [41]="1" [42]="1" [43]="0" [44]="0" [45]="0" [46]="1" [47]="0" [48]="0" [49]="0" [50]="0" [51]="0" [52]="0" [53]="0" [$((n+1))]="1" [$((n+2))]="1" [$((n+3))]="0" [$((n+4))]="0" [$((n+5))]="0" [$((n+6))]="0" [$((n+7))]="0" [$((n+8))]="0" [$((n+9))]="0" [$((n+10))]="0" [$((n+11))]="0" )
 
 MANUAL_TESTCASE=( [0]="bluetooth" [1]="hdmi" [2]="sdio_wifi" [3]="power" [$((n+1))]="" )
 
@@ -148,7 +148,7 @@ if [ $BOARD_CONFIG = "BF609-EZKIT-USBHOST" ] ; then
     BOARD_TYPE=BF609-EZKIT
 
     AUTO_RUN_STATUS[1]="1"; AUTO_RUN_STATUS[11]="1"; AUTO_RUN_STATUS[12]="1"; AUTO_RUN_STATUS[24]="1"; AUTO_RUN_STATUS[29]="1"; AUTO_RUN_STATUS[30]="1"; AUTO_RUN_STATUS[34]="1"; AUTO_RUN_STATUS[39]="1"; AUTO_RUN_STATUS[43]="1"; AUTO_RUN_STATUS[44]="1"; AUTO_RUN_STATUS[47]="1"; AUTO_RUN_STATUS[49]="1";
-    AUTO_RUN_STATUS[$((n+7))]="1";
+    AUTO_RUN_STATUS[$((n+7))]="1"; AUTO_RUN_STATUS[$((n+11))]="1";
 fi
 
 if [ $BOARD_CONFIG = "BF609-EZKIT-CAN" ] ; then
@@ -662,6 +662,53 @@ if [ ${AUTO_RUN_STATUS[$((n+7))]} -eq 1 ] ; then
 
     done
 fi
+
+
+##################################### XIP TEST #####################################
+
+if [ ${AUTO_RUN_STATUS[$((n+11))]} -eq 1 ] ; then
+    APP_FORMAT="fdpic shared-flat"
+    SUB_TESTCASE="xip_userspace kernel_xip fs_xip"
+
+    for sub_test in $SUB_TESTCASE
+    do
+
+        for format in $APP_FORMAT
+        do
+            FORMAT=`echo $format|tr 'a-z' 'A-Z'`
+            echo "Start testing $sub_test in $format mode..."
+
+            use_output_bak 
+            cp $SRC_ROOT/config.user.policy $SRC_ROOT/.config
+
+            cd $TESTSUITES_DIR/xip
+            ./build_${sub_test}_kernel.exp $BOARD_TYPE $format >/dev/null 2>&1
+
+            if ( [ $sub_test == "xip_userspace" ] && [ ! -f $IMAGE_DIR/uImage ] ) || ( [ $sub_test == "kernel_xip" ] && [ ! -f $IMAGE_DIR/vmImage ] ) || ( [ $sub_test == "fs_xip" ] && ( [ ! -f $IMAGE_DIR/vmImage ] || [ ! -f $IMAGE_DIR/rootfs.romfs ] ) )
+            then
+                echo "$0:   Error, failed."
+                tail -50 ./build_${sub_test}_${format}_kernel_log
+            else
+                ./${sub_test}_test.exp $BOARD_TYPE $format >/dev/null  2>&1
+            fi
+
+            copy_image_config "$sub_test.$format"
+            mv $TESTSUITES_DIR/xip/*_log  $THIS_LOG
+
+            echo "End testing $sub_test..."
+            sleep 10
+
+            if [ $RESET_BOARD -eq 1  ] ; then
+                cd $TESTSUITES_DIR/common
+                ./reset_board.exp $BOARD_TYPE > /dev/null 2>&1
+                sleep 10
+            fi
+        done
+
+    done
+
+fi
+
 
 ################# TEST BOOT UCLINUX_DIST AND MOUNT JFFS2 FS FROM SPI FLASH ########################
 
